#
# See https://kubernetes.io/docs/concepts/services-networking/ingress/
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: rest-server
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rest-server
                port:
                  number: 5000